apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-speech-translation
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: kubernetes-speech-translation
  template:
    metadata:
      labels:
        app: kubernetes-speech-translation
    spec:
      containers:
      - name: kubernetes-speech-translation
        image: docker.io/sohamb16/speech-translation:latest #running from openshift
        imagePullPolicy: Always  
        
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-speech-translation
spec:
  selector:
    app: kubernetes-speech-translation
  ports:
  - port: 8080
    targetPort: 7860