apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-speech-translation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-speech-translation
  template:
    metadata:
      labels:
        app: kubernetes-speech-translation
    spec:
      containers:
      - name: kubernetes-speech-translation
        image: docker.io/sohamb16/speech-translation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7860
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-speech-translation
spec:
  selector:
    app: kubernetes-speech-translation
  ports:
  - port: 7860
    targetPort: 7860

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: speech-translation-route
spec:
  to:
    kind: Service
    name: kubernetes-speech-translation
  port:
    targetPort: 7860
  tls:
    termination: edge
